name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  ci:
    name: ci (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: linux-x64
            os: ubuntu-latest
          - target: linux-arm64
            os: ubuntu-24.04-arm
          - target: macos-arm64
            os: macos-14
          - target: macos-x64
            os: macos-15-intel
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - run: mise run ci
